site_name: Kraby
site_description: Open source hexapod robot for deep learning research.
copyright: "This project is under GNU General Public License v3.0."
repo_url: https://github.com/erdnaxe/kraby

nav:
  - Home: index.md
  - Building the robot:
      - Build the structure: build_the_structure.md
      - Build the electronics: build_the_electronics.md
      - Install NanoPi Linux with MPU9250 support: install_nanopi_linux.md
  - Using the robot:
      - Use the internal motion unit: use_mpu9250.md
      - Use the servomotors: use_motors.md
  - Simulation:
      - URDF description: urdf_description.md
      - OpenAI Gym environments: gym_environments.md
      - Proximal Policy Optimization: implementations_ppo.md
      - Training one leg: training_one_leg.md
      - Transfer to the real world: transfer_real_world.md
  - About:
      - Contributing: contributing.md
      - License: license.md

theme:
  name: readthedocs

extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - admonition
